name: 🐧 Linux Build
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        toolchain: [ stable, 1.61.0 ]
        type: [ release ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - uses: actions/cache@v3
        with:
          path: |
            target
          key: linux-default-${{github.ref}}-${{github.sha}}
          restore-keys: |
            linux-default-${{github.ref}}-${{github.sha}}

      - name: Build Release
        run: cargo build --release
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0"
